# Generated by Django 5.1.5 on 2025-02-01 07:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='Untitled Note', max_length=200),
        ),
        migrations.AddField(
            model_name='pdf',
            name='name',
            field=models.CharField(default='Untitled PDF', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='Untitled Video', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
