# Generated by Django 5.1.5 on 2025-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contents', '0002_note_name_pdf_name_video_file_video_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='media/pdfs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
